version: '3.8'

services:
  backend:
    build:
      context: ./backend
      # Utilize um Dockerfile específico para desenvolvimento (ver passo 2)
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - CONFIG_PATH=/app/.env
    ports:
      - "8080:8080"  # ajuste a porta conforme sua aplicação backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: