import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >      {/* Navbar */}
        <div className="navbar bg-base-100 shadow-lg">
          <div className="navbar-start">
            <a className="btn btn-ghost normal-case text-xl">Sistema PIT</a>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
